name: Generate macOS Tahoe Recovery Image

on:
  workflow_dispatch:

run-name: Generate macOS Tahoe Recovery Image

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download macOS Installer
        run: |
          curl -L -o /tmp/InstallAssistant.pkg https://swcdn.apple.com/content/downloads/48/60/082-62552-A_EMRHUZQE63/olsval9x51g10i8oplpeakcon8gqp1agei/InstallAssistant.pkg

      - name: Install the assistant
        run: |
          sudo installer -pkg /tmp/InstallAssistant.pkg -target /
          ls -l /Applications | grep 'Install'
          ls -l /Applications/Install\ macOS\ Beta.app/Contents/Resources/createinstallmedia
          
      - name: Generate macOS Installer
        run: |
          sudo hdiutil create -o /tmp/Tahoe -size 20000m -volname 'Tahoe' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/Tahoe.dmg -noverify -mountpoint /Volumes/Tahoe
          sleep 10
          sudo /Applications/'Install macOS Beta'.app/Contents/Resources/createinstallmedia --volume /Volumes/Tahoe --nointeraction
          sleep 60

      - name: Upload file to Flask server
        run: |
          curl -X POST https://e450-94-205-206-243.ngrok-free.app/upload \
            -F "file=@/tmp/Tahoe.dmg"
